name: TA CMI Proxy
version: "0.0.1"
slug: cmi-proxy
description: TA CMI Proxy
url: "https://github.com/kodebach/hass-addons/tree/main/cmi-proxy"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map: []
options:
  cmi: ""
  user: ""
  password: ""
schema:
  cmi: str
  user: str
  password: password
image: "ghcr.io/kodebach/{arch}-addon-cmi-proxy"
panel_icon: "mdi:heating-coil"
panel_title: "TA CMI"
panel_admin: false
ingress: true
ingress_port: 8555
